# Generated by Django 3.2.21 on 2023-10-08 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_starting', models.DateTimeField(auto_now_add=True)),
                ('date_ending', models.DateTimeField(blank=True, null=True)),
                ('event_place', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketID', models.BigIntegerField()),
                ('ticketNum', models.BigIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Is_available', models.BigIntegerField()),
                ('date_bought', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ticketSystem',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ticket')),
                ('reservation', models.BigIntegerField()),
                ('regular_ticket', models.BigIntegerField()),
            ],
            bases=('app.ticket', models.Model),
        ),
    ]
