# Generated by Django 3.2.21 on 2023-10-11 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('age', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Is_available',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticketID',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticketNum',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out of stock', 'Out of stock'), ('Bought', 'Bought')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_starting',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(choices=[('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Utah Jazz', 'Utah Jazz'), ('San Antonio Spurs', 'San Antonio Spurs'), ('UMilwaukee Bucks', 'UMilwaukee Bucks'), ('Orlando Magic', 'Orlando Magic'), ('Toronto Raptors', 'Toronto Raptors')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.FloatField(),
        ),
    ]
