# Generated by Django 3.2.21 on 2023-10-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231011_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Utah Jazz', 'Utah Jazz'), ('San Antonio Spurs', 'San Antonio Spurs'), ('UMilwaukee Bucks', 'UMilwaukee Bucks'), ('Orlando Magic', 'Orlando Magic'), ('Toronto Raptors', 'Toronto Raptors')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('date_ending', models.DateTimeField(blank=True, null=True)),
                ('event_place', models.CharField(choices=[('Gainbridge Fieldhouse, Indianapolis, IN', 'Gainbridge Fieldhouse, Indianapolis, IN')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out of stock', 'Out of stock'), ('Bought', 'Bought')], max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='events',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Reservation', 'Reservation'), ('Regular ticket', 'Regular ticket')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_bought',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ticketSystem',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.event'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ticket'),
        ),
    ]
