# Generated by Django 3.2.21 on 2023-10-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231013_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date_bought',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='order',
            name='date_bought',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
