# Generated by Django 3.2.21 on 2023-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Reservation', 'Reservation'), ('Balcony level', 'Balcony level'), ('Club level', 'Club level'), ('Lower level', 'Lower level'), ('Suite', 'Suite'), ('Courtside', 'Courtside')], max_length=100, null=True),
        ),
    ]
